/**
 * Created by linpengteng on ,2021/5/17.
 */

'use strict';

define(function(){

    return {
        "success":true,
        "msg":null,
        "obj":{
            "CITY_POPULARIZE":{
                "localCity": "宁波北仑",
                "province": {},
                "city": {},
                "area":{}
            },
            "PRODUCT_POPULARIZE_1":{
                "popularizeName":"热卖商品",
                "modelList":[
                    {
                        "id":1,
                        "title":"伊丽莎白雅顿",
                        "shortTitle":"伊丽莎白雅顿",
                        "description":"伊丽莎白雅顿5th第五大道女士香水30/75/125ml持久清新优雅淡香水",
                        "price":699,
                        "productId": "productid1",
                        "picPath":"test_b1.jpg",
                        "name":"热卖商品",
                        "popularizeCode":"PRODUCT_POPULARIZE_1"
                    },
                    {
                        "id":2,
                        "title":"伊丽莎白雅顿",
                        "shortTitle":"伊丽莎白雅顿",
                        "description":"伊丽莎白雅顿5th第五大道女士香水30/75/125ml持久清新优雅淡香水",
                        "price":619.00,
                        "productId": "productid1",
                        "picPath":"test_b2.jpg",
                        "name":"热卖商品",
                        "popularizeCode":"PRODUCT_POPULARIZE_1"
                    },
                    {
                        "id":null,
                        "title":"伊丽莎白雅顿",
                        "shortTitle":"伊丽莎白雅顿",
                        "description":"伊丽莎白雅顿5th第五大道女士香水30/75/125ml持久清新优雅淡香水",
                        "price":577.00,
                        "productId": "productid1",
                        "picPath":"test_b3.jpg",
                        "name":"热卖商品",
                        "popularizeCode":"PRODUCT_POPULARIZE_1"
                    },
                    {
                        "id":null,
                        "title":"伊丽莎白雅顿",
                        "shortTitle":"伊丽莎白雅顿",
                        "description":"伊丽莎白雅顿5th第五大道女士香水30/75/125ml持久清新优雅淡香水",
                        "price":719.00,
                        "productId": "productid1",
                        "picPath":"test_b4.jpg",
                        "name":"热卖商品",
                        "popularizeCode":"PRODUCT_POPULARIZE_1"
                    },
                    {
                        "id":null,
                        "title":"伊丽莎白雅顿",
                        "shortTitle":"伊丽莎白雅顿",
                        "description":"伊丽莎白雅顿5th第五大道女士香水30/75/125ml持久清新优雅淡香水",
                        "price":449.00,
                        "productId": "productid1",
                        "picPath":"test_b5.jpg",
                        "name":"热卖商品",
                        "popularizeCode":"PRODUCT_POPULARIZE_1"
                    },
                    {
                        "id":null,
                        "title":"伊丽莎白雅顿",
                        "shortTitle":"伊丽莎白雅顿",
                        "description":"伊丽莎白雅顿5th第五大道女士香水30/75/125ml持久清新优雅淡香水",
                        "price":539.00,
                        "productId": "productid1",
                        "picPath":"test_b6.jpg",
                        "name":"热卖商品",
                        "popularizeCode":"PRODUCT_POPULARIZE_1"
                    },
                    {
                        "id":null,
                        "title":"伊丽莎白雅顿",
                        "shortTitle":"伊丽莎白雅顿",
                        "description":"伊丽莎白雅顿5th第五大道女士香水30/75/125ml持久清新优雅淡香水",
                        "price":609.00,
                        "productId": "productid1",
                        "picPath":"test_b7.jpg",
                        "name":"热卖商品",
                        "popularizeCode":"PRODUCT_POPULARIZE_1"
                    },
                    {
                        "id":null,
                        "title":"伊丽莎白雅顿",
                        "shortTitle":"伊丽莎白雅顿",
                        "description":"伊丽莎白雅顿5th第五大道女士香水30/75/125ml持久清新优雅淡香水",
                        "price":609.00,
                        "productId": "productid1",
                        "picPath":"test_b2.jpg",
                        "name":"热卖商品",
                        "popularizeCode":"PRODUCT_POPULARIZE_1"
                    },
                    {
                        "id":null,
                        "title":"伊丽莎白雅顿",
                        "shortTitle":"伊丽莎白雅顿",
                        "description":"伊丽莎白雅顿5th第五大道女士香水30/75/125ml持久清新优雅淡香水",
                        "price":609.00,
                        "productId": "productid1",
                        "picPath":"test_b3.jpg",
                        "name":"热卖商品",
                        "popularizeCode":"PRODUCT_POPULARIZE_1"
                    }
                ]
            },
            "MEMBER_POPULARIZE_1":{
                "popularizeName":"热门企业",
                "modelList":[
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo1.jpg",
                        "memberId": "memberId1",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo2.jpg",
                        "memberId": "memberId2",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo3.jpg",
                        "memberId":"memberId3",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo4.jpg",
                        "memberId":"memberId4",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo5.jpg",
                        "memberId":"memberId5",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo1.jpg",
                        "memberId":"memberId6",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo2.jpg",
                        "memberId":"memberId7",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_3",
                        "logoPath":"test_logo1.jpg",
                        "memberId":"memberId8",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_4",
                        "logoPath":"test_logo1.jpg",
                        "memberId":"memberId9",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo5.jpg",
                        "memberId":"memberId10",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo1.jpg",
                        "memberId":"memberId11",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo2.jpg",
                        "memberId":"memberId12",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo3.jpg",
                        "memberId":"memberId13",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo4.jpg",
                        "memberId":"memberId14",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo5.jpg",
                        "memberId":"memberId15",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    },
                    {
                        "name":"热门企业",
                        "popularizeCode":"MEMBER_POPULARIZE_1",
                        "logoPath":"test_logo1.jpg",
                        "memberId":"memberId16",
                        "picPath":"test_a1.jpg",
                        "description":"测试"
                    }
                ]
            },
            "MEMBER_PRODUCT_POPULARIZE_1":{
                "popularizeName":"新品推荐",
                "modelList":[
                    {
                        "name":"新品推荐",
                        "popularizeCode":"MEMBER_PRODUCT_POPULARIZE_1",
                        "logoPath":"test_logo1.jpg",
                        "memberId":"memberid1",
                        "picPath1":"test_a1.jpg",
                        "picPath2":"test_a2.jpg",
                        "picPath3":"test_a3.jpg",
                        "sketch1": "GXG服装有限公司",
                        "description1":"GXG是宁波中哲慕尚控股有限公司旗下男装品牌。针对消费年龄段：22-38岁，设计类型：趋向年轻化，个性，有态度的细节廓形品牌。从2015年起，针对更多90-95后独立自我的新生代青年的时髦街头自由态度来改变设计风格，获得更多市场年起人的喜爱。2016年品牌与众多独立艺术家进行合作联名，gxg.jeans品牌更是与Bigbang所喜爱的潮流代表“KRUNK”进行跨界合作。",
                        "description2":"GXG2016秋将更多生活舒适度与色彩、花型进行结合，通过更具生活感的简约造型，将年轻消费群体所需求的态度展现。更多廓形，趣味，运动，线条及暗黑街头运动的设计概念，符合当下年轻消费群体需求。",
                        "description3":"2013年-2014年，GXG中国音乐之旅五月天、成龙、任贤齐、李宗盛、张震岳、邓紫棋共计开启22场演唱会记录，同年开启GXG为爱点亮一座城圣诞亮灯计划，并于2014年初开启GXG在国内时尚男装品类首场实景服装品牌秀；",
                        "generalInfoList":[
                            {
                                "id":1,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":120,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            },
                            {
                                "id":2,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":110.00,
                                "productId": "productid1",
                                "picPath":"test_a5.jpg"
                            },
                            {
                                "id":3,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":108.00,
                                "productId": "productid1",
                                "picPath":"test_a6.jpg"
                            },
                            {
                                "id":4,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":151.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            },
                            {
                                "id":5,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":132.00,"productId": "productid1","picPath":"test_a5.jpg"
                            },
                            {
                                "id":6,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":108.00,
                                "productId": "productid1",
                                "picPath":"test_a6.jpg"
                            },
                            {
                                "id":7,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":160.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            }
                        ]
                    },
                    {
                        "name":"新品推荐",
                        "popularizeCode":"MEMBER_PRODUCT_POPULARIZE_1",
                        "logoPath":"test_logo2.jpg",
                        "memberId": "memberid2",
                        "picPath1":"test_a1.jpg",
                        "picPath2":"test_a2.jpg",
                        "picPath3":"test_a3.jpg",
                        "description1":"GXG是宁波中哲慕尚控股有限公司旗下男装品牌。针对消费年龄段：22-38岁，设计类型：趋向年轻化，个性，有态度的细节廓形品牌。从2015年起，针对更多90-95后独立自我的新生代青年的时髦街头自由态度来改变设计风格，获得更多市场年起人的喜爱。2016年品牌与众多独立艺术家进行合作联名，gxg.jeans品牌更是与Bigbang所喜爱的潮流代表“KRUNK”进行跨界合作。",
                        "description2":"GXG2016秋将更多生活舒适度与色彩、花型进行结合，通过更具生活感的简约造型，将年轻消费群体所需求的态度展现。更多廓形，趣味，运动，线条及暗黑街头运动的设计概念，符合当下年轻消费群体需求。",
                        "description3":"2013年-2014年，GXG中国音乐之旅五月天、成龙、任贤齐、李宗盛、张震岳、邓紫棋共计开启22场演唱会记录，同年开启GXG为爱点亮一座城圣诞亮灯计划，并于2014年初开启GXG在国内时尚男装品类首场实景服装品牌秀；",
                        "generalInfoList":[
                            {
                                "id":8,
                                "title":"GXG男装2018夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":155.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            },
                            {
                                "id":9,
                                "title":"GXG男装2018夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":104.00,
                                "productId": "productid1",
                                "picPath":"test_a5.jpg"
                            },
                            {
                                "id":10,
                                "title":"GXG男装2018夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":121.00,
                                "productId": "productid1",
                                "picPath":"test_a6.jpg"
                            },
                            {
                                "id":11,
                                "title":"GXG男装2018夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":104.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            },
                            {
                                "id":12,
                                "title":"GXG男装2018夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":180.00,"productId": "productid1","picPath":"test_a5.jpg"
                            },
                            {
                                "id":13,
                                "title":"GXG男装2018夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":117.00,
                                "productId": "productid1",
                                "picPath":"test_a6.jpg"
                            },
                            {
                                "id":14,
                                "title":"GXG男装2018夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":132.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            }
                        ]
                    },
                    {
                        "name":"新品推荐",
                        "popularizeCode":"MEMBER_PRODUCT_POPULARIZE_1",
                        "logoPath":"test_logo3.jpg",
                        "memberId": "memberid3",
                        "picPath1":"test_a1.jpg",
                        "picPath2":"test_a2.jpg",
                        "picPath3":"test_a3.jpg",
                        "description1":"GXG是宁波中哲慕尚控股有限公司旗下男装品牌。针对消费年龄段：22-38岁，设计类型：趋向年轻化，个性，有态度的细节廓形品牌。从2015年起，针对更多90-95后独立自我的新生代青年的时髦街头自由态度来改变设计风格，获得更多市场年起人的喜爱。2016年品牌与众多独立艺术家进行合作联名，gxg.jeans品牌更是与Bigbang所喜爱的潮流代表“KRUNK”进行跨界合作。",
                        "description2":"GXG2016秋将更多生活舒适度与色彩、花型进行结合，通过更具生活感的简约造型，将年轻消费群体所需求的态度展现。更多廓形，趣味，运动，线条及暗黑街头运动的设计概念，符合当下年轻消费群体需求。",
                        "description3":"2013年-2014年，GXG中国音乐之旅五月天、成龙、任贤齐、李宗盛、张震岳、邓紫棋共计开启22场演唱会记录，同年开启GXG为爱点亮一座城圣诞亮灯计划，并于2014年初开启GXG在国内时尚男装品类首场实景服装品牌秀；",
                        "generalInfoList":[
                            {
                                "id":15,
                                "title":"GXG男装2019夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":111.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            },
                            {
                                "id":16,
                                "title":"GXG男装2019夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":123.00,
                                "productId": "productid1",
                                "picPath":"test_a5.jpg"
                            },
                            {
                                "id":17,
                                "title":"GXG男装2019夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":111.00,
                                "productId": "productid1",
                                "picPath":"test_a6.jpg"
                            },
                            {
                                "id":18,
                                "title":"GXG男装2019夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":142.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            },
                            {
                                "id":19,
                                "title":"GXG男装2019夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":118.00,
                                "productId": "productid1",
                                "picPath":"test_a5.jpg"
                            },
                            {
                                "id":20,
                                "title":"GXG男装2019夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":230.00,
                                "productId": "productid1",
                                "picPath":"test_a6.jpg"
                            },
                            {
                                "id":21,
                                "title":"GXG男装2019夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":430.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            }
                        ]
                    },
                    {
                        "name":"新品推荐",
                        "popularizeCode":"MEMBER_PRODUCT_POPULARIZE_1",
                        "logoPath":"test_logo4.jpg",
                        "memberId": "memberid4",
                        "picPath1":"test_a1.jpg",
                        "picPath2":"test_a2.jpg",
                        "picPath3":"test_a3.jpg",
                        "description1":"GXG是宁波中哲慕尚控股有限公司旗下男装品牌。针对消费年龄段：22-38岁，设计类型：趋向年轻化，个性，有态度的细节廓形品牌。从2015年起，针对更多90-95后独立自我的新生代青年的时髦街头自由态度来改变设计风格，获得更多市场年起人的喜爱。2016年品牌与众多独立艺术家进行合作联名，gxg.jeans品牌更是与Bigbang所喜爱的潮流代表“KRUNK”进行跨界合作。",
                        "description2":"GXG2016秋将更多生活舒适度与色彩、花型进行结合，通过更具生活感的简约造型，将年轻消费群体所需求的态度展现。更多廓形，趣味，运动，线条及暗黑街头运动的设计概念，符合当下年轻消费群体需求。",
                        "description3":"2013年-2014年，GXG中国音乐之旅五月天、成龙、任贤齐、李宗盛、张震岳、邓紫棋共计开启22场演唱会记录，同年开启GXG为爱点亮一座城圣诞亮灯计划，并于2014年初开启GXG在国内时尚男装品类首场实景服装品牌秀；",
                        "generalInfoList":[
                            {
                                "id":22,
                                "title":"GXG男装2020夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":165.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            },
                            {
                                "id":23,
                                "title":"GXG男装2020夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":139.00,
                                "productId": "productid1",
                                "picPath":"test_a5.jpg"
                            },
                            {
                                "id":24,
                                "title":"GXG男装2020夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":121.00,
                                "productId": "productid1",
                                "picPath":"test_a6.jpg"
                            },
                            {
                                "id":25,
                                "title":"GXG男装2020夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":131.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            },
                            {
                                "id":26,
                                "title":"GXG男装2020夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":247.00,
                                "productId": "productid1",
                                "picPath":"test_a5.jpg"
                            },
                            {
                                "id":27,
                                "title":"GXG男装2020夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":399.00,
                                "productId": "productid1",
                                "picPath":"test_a6.jpg"
                            },
                            {
                                "id":28,
                                "title":"GXG男装2020夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":268.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            }
                        ]
                    },
                    {
                        "name":"新品推荐",
                        "popularizeCode":"MEMBER_PRODUCT_POPULARIZE_1",
                        "logoPath":"test_logo5.jpg",
                        "memberId": "memberid5",
                        "picPath1":"test_a1.jpg",
                        "picPath2":"test_a2.jpg",
                        "picPath3":"test_a3.jpg",
                        "description1":"GXG是宁波中哲慕尚控股有限公司旗下男装品牌。针对消费年龄段：22-38岁，设计类型：趋向年轻化，个性，有态度的细节廓形品牌。从2015年起，针对更多90-95后独立自我的新生代青年的时髦街头自由态度来改变设计风格，获得更多市场年起人的喜爱。2016年品牌与众多独立艺术家进行合作联名，gxg.jeans品牌更是与Bigbang所喜爱的潮流代表“KRUNK”进行跨界合作。",
                        "description2":"GXG2016秋将更多生活舒适度与色彩、花型进行结合，通过更具生活感的简约造型，将年轻消费群体所需求的态度展现。更多廓形，趣味，运动，线条及暗黑街头运动的设计概念，符合当下年轻消费群体需求。",
                        "description3":"2013年-2014年，GXG中国音乐之旅五月天、成龙、任贤齐、李宗盛、张震岳、邓紫棋共计开启22场演唱会记录，同年开启GXG为爱点亮一座城圣诞亮灯计划，并于2014年初开启GXG在国内时尚男装品类首场实景服装品牌秀；",
                        "generalInfoList":[
                            {
                                "id":29,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":100.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            },
                            {
                                "id":30,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":100.00,
                                "productId": "productid1",
                                "picPath":"test_a5.jpg"
                            },
                            {
                                "id":31,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":100.00,
                                "productId": "productid1",
                                "picPath":"test_a6.jpg"
                            },
                            {
                                "id":32,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":100.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            },
                            {
                                "id":33,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":100.00,"productId": "productid1","picPath":"test_a5.jpg"
                            },
                            {
                                "id":34,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":100.00,
                                "productId": "productid1",
                                "picPath":"test_a6.jpg"
                            },
                            {
                                "id":35,
                                "title":"GXG男装,2021夏季新品",
                                "shortTitle":"GXG男装",
                                "description":"GXG男装",
                                "price":100.00,
                                "productId": "productid1",
                                "picPath":"test_a4.jpg"
                            }
                        ]
                    },
                ]
            },
            "INDEX_BANNER":{
                "popularizeName":"首页轮播",
                "modelList":[
                    {
                        "picPath":"test_banner_1.jpg",
                        "href":"#",
                        "name":"首页轮播",
                        "popularizeCode":"INDEX_BANNER"
                    },
                    {
                        "picPath":"test_banner_2.jpg",
                        "href":"#",
                        "name":"首页轮播",
                        "popularizeCode":"INDEX_BANNER"
                    },
                    {
                        "picPath":"test_banner_3.jpg",
                        "href":"#",
                        "name":"首页轮播",
                        "popularizeCode":"INDEX_BANNER"
                    },
                    {
                        "picPath":"test_banner_4.jpg",
                        "href":"#",
                        "name":"首页轮播",
                        "popularizeCode":"INDEX_BANNER"
                    },
                    {
                        "picPath":"test_banner_5.jpg",
                        "href":"#",
                        "name":"首页轮播",
                        "popularizeCode":"INDEX_BANNER"
                    },
                    {
                        "picPath":"test_banner_6.jpg",
                        "href":"#",
                        "name":"首页轮播",
                        "popularizeCode":"INDEX_BANNER"
                    }
                ]
            }
        }
    }

});
